name: IS
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas=2.3.3=py311ha5e6156_0
  - numpy=2.3.1
  - python=3.11.14
  - pyqt=5.15.11=py311h7c55f98_2
  - scipy=1.16.2
  - scikit-learn=1.7.2=py311h8a15ebc_0
  - matplotlib
  - seaborn=0.13.2=py311haa95532_3
  - msys2-conda-epoch=20160418=1
  - tornado=6.5.1
  - libclang13=21.1.2
  - tk=8.6.15=hf199647_0
  - vc=14.3=h2df5915_10
  - libglib=2.84.2
  - kiwisolver=1.4.8
  - gstreamer=1.24.11=h233a61a_0
  - mkl_fft=1.3.10
  - contourpy=1.3.1
  - bottleneck=1.4.2
  - libdeflate=1.22
  - libsqlite=3.50.4
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - ucrt=10.0.22621.0
  - libwebp-base=1.6.0=h4d5522a_0
  - pyparsing=3.2.0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - pip=25.2
  - matplotlib-base=3.10.6
  - liblapack=3.9.0
  - m2w64-gmp=6.1.0=2
  - libtiff=4.7.0
  - icu=75.1=he0c23c2_0
  - ply=3.11=pyhd8ed1ab_3
  - glib-tools=2.84.2
  - python_abi=3.11=2_cp311
  - glib=2.84.2
  - libvorbis=1.3.7=h5112557_2
  - libxml2=2.13.8
  - pcre2=10.42
  - libcblas=3.9.0
  - tbb-devel=2021.13.0
  - toml=0.10.2=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h9f73205_0
  - mkl_random=1.2.8
  - bzip2=1.0.8=h2bbff1b_6
  - pytz=2025.2=py311haa95532_0
  - mkl-service=2.4.1
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - libiconv=1.18=hc1393d2_2
  - m2w64-gcc-libs=5.3.0=7
  - sip=6.10.0
  - fonttools=4.60.1=py311h02ab6af_0
  - openssl=3.6.0
  - tzdata=2025b=h04d1e81_0
  - libintl=0.22.5=h5728263_3
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - libxcb=1.16=h013a479_1
  - six=1.17.0=py311haa95532_0
  - setuptools=72.1.0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - tomli=2.3.0=pyhcf101f3_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - pillow=10.4.0=py311h5592be9_1
  - libffi=3.4.4
  - wheel=0.45.1=py311haa95532_0
  - ca-certificates=2025.11.4
  - packaging=25.0=pyh29332c3_1
  - xz=5.6.4
  - numexpr=2.11.0
  - freetype=2.13.3
  - vc14_runtime=14.44.35208=h4927774_10
  - tbb=2021.13.0
  - zstd=1.5.7=hbeecb71_2
  - numpy-base=2.3.1
  - libogg=1.3.5=h2466b09_1
  - sqlite=3.50.2
  - pthread-stubs=0.3
  - qt-main=5.15.15=h9151539_4
  - mkl=2023.2.0
  - blas=1.0=mkl
  - joblib=1.5.2=pyhd8ed1ab_0
  - libjpeg-turbo=3.1.0
  - krb5=1.21.3=hdf4eb48_0
  - zlib=1.3.1=h02ab6af_0
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - cycler=0.11.0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - openjpeg=2.5.2
  - m2w64-gcc-libs-core=5.3.0=7
  - libblas=3.9.0
  - lcms2=2.17=hbcf6048_0
  - libpng=1.6.50=h7351971_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - libzlib=1.3.1=h02ab6af_0
  - expat=2.7.3
  - lerc=4.0.0=h5da7b33_0
  - intel-openmp=2025.0.0
  - pytest
  - pytest-qt
  - pytest-mock
prefix: C:\Users\yogar\.conda\envs\IS
